export const GROUPS = ["Housing & Urbanism", "Transit & Streets", "Volunteering", "Government & Political", "Suburban Councils"];

export const DEFAULT_SOURCES = [
  { name: "Sightline Institute", group: "Housing & Urbanism", url: "https://www.sightline.org/tag/events/" },
  { name: "The Urbanist", group: "Housing & Urbanism", url: "https://www.theurbanist.org/upcoming-events/" },
  { name: "Futurewise", group: "Housing & Urbanism", url: "" },
  { name: "Share the Cities", group: "Housing & Urbanism", url: "" },
  { name: "Seattle For Everyone", group: "Housing & Urbanism", url: "" },
  { name: "House Our Neighbors", group: "Housing & Urbanism", url: "" },
  { name: "Transportation Choices Coalition", group: "Transit & Streets", url: "https://transportationchoices.org/events/" },
  { name: "Sound Transit (board & public meetings)", group: "Transit & Streets", url: "https://www.soundtransit.org/get-to-know-us/news-events/calendar" },
  { name: "Seattle Neighborhood Greenways", group: "Transit & Streets", url: "" },
  { name: "Habitat for Humanity Seattle-King County", group: "Volunteering", url: "https://www.habitatskc.org/how-to-help/volunteer/" },
  { name: "United Way of King County", group: "Volunteering", url: "https://volunteer.uwkc.org" },
  { name: "VolunteerMatch (Seattle)", group: "Volunteering", url: "" },
  { name: "Seattle City Council", group: "Government & Political", url: "https://www.seattle.gov/council/calendar" },
  { name: "King County Council", group: "Government & Political", url: "https://kingcounty.gov/en/dept/council/governance-leadership/county-council/committees/county-council-meetings" },
  { name: "King County Democrats", group: "Government & Political", url: "" },
  { name: "Bellevue City Council", group: "Suburban Councils", url: "https://bellevuewa.gov/city-government/city-council/council-meetings" },
  { name: "Redmond City Council", group: "Suburban Councils", url: "https://www.redmond.gov/189/City-Council" },
  { name: "Kirkland City Council", group: "Suburban Councils", url: "https://www.kirklandwa.gov/Whats-Happening/Council-Meetings" },
  { name: "Renton City Council", group: "Suburban Councils", url: "" },
  { name: "Kent City Council", group: "Suburban Councils", url: "" },
  { name: "Auburn City Council", group: "Suburban Councils", url: "" },
  { name: "Federal Way City Council", group: "Suburban Councils", url: "" },
  { name: "Shoreline City Council", group: "Suburban Councils", url: "" },
  { name: "Burien City Council", group: "Suburban Councils", url: "" },
  { name: "Issaquah City Council", group: "Suburban Councils", url: "" },
  { name: "Sammamish City Council", group: "Suburban Councils", url: "" },
  { name: "Bothell City Council", group: "Suburban Councils", url: "" },
  { name: "Kenmore City Council", group: "Suburban Councils", url: "" },
  { name: "Mercer Island City Council", group: "Suburban Councils", url: "" },
];
